export const DESIGN_TOKENS = {
  surfaces: {
    app: 'bg-zinc-50',
    appSoft: 'bg-zinc-50/50',
    canvas: 'bg-white',
    muted: 'bg-zinc-50/80',
    overlay: 'bg-zinc-950/60',
  },
  text: {
    primary: 'text-zinc-900',
    secondary: 'text-zinc-700',
    muted: 'text-zinc-500',
    subtle: 'text-zinc-400',
    inverse: 'text-white',
    brand: 'text-tertiary',
    brandStrong: 'text-primary',
  },
  border: {
    default: 'border-zinc-200',
    soft: 'border-zinc-100',
    strong: 'border-zinc-300',
    brand: 'border-teal-300',
  },
  interactive: {
    primary: 'bg-tertiary text-primary hover:bg-primary hover:text-on-primary focus:ring-tertiary',
    secondary: 'bg-white text-zinc-700 border border-zinc-200 hover:bg-zinc-50 hover:border-zinc-300 focus:ring-zinc-300',
    ghost: 'text-zinc-600 hover:bg-zinc-100 hover:text-zinc-900 focus:ring-zinc-300',
  },
  brand: {
    surface: 'bg-teal-50',
    surfaceSoft: 'bg-teal-50/80',
    border: 'border-teal-300',
    text: 'text-teal-800',
    textStrong: 'text-teal-900',
    icon: 'text-teal-700',
    accent: 'bg-teal-600',
    accentHover: 'bg-teal-700',
  },
  semantic: {
    success: {
      surface: 'bg-emerald-50',
      border: 'border-emerald-200',
      text: 'text-emerald-700',
      textStrong: 'text-emerald-900',
      icon: 'text-emerald-600',
      badge: 'bg-emerald-50 text-emerald-700 border border-emerald-200',
    },
    warning: {
      surface: 'bg-amber-50',
      border: 'border-amber-200',
      text: 'text-amber-700',
      textStrong: 'text-amber-900',
      icon: 'text-amber-600',
      badge: 'bg-amber-50 text-amber-700 border border-amber-200',
    },
    danger: {
      surface: 'bg-rose-50',
      border: 'border-rose-200',
      text: 'text-rose-700',
      textStrong: 'text-rose-900',
      icon: 'text-rose-600',
      badge: 'bg-rose-50 text-rose-700 border border-rose-200',
    },
    info: {
      surface: 'bg-blue-50',
      border: 'border-blue-200',
      text: 'text-blue-700',
      textStrong: 'text-blue-900',
      icon: 'text-blue-600',
      badge: 'bg-blue-50 text-blue-700 border border-blue-200',
    },
    neutral: {
      surface: 'bg-zinc-50',
      border: 'border-zinc-200',
      text: 'text-zinc-700',
      textStrong: 'text-zinc-900',
      icon: 'text-zinc-500',
      badge: 'bg-zinc-100 text-zinc-700 border border-zinc-200',
    },
  },
  chart: {
    primary: '#0F2A3B',
    secondary: '#4F6B7C',
    tertiary: '#0E9F8E',
    quaternary: '#F1F5F7',
    success: '#0E9F8E',
    info: '#4F6B7C',
    warning: '#4F6B7C',
    danger: '#0F2A3B',
    muted: '#F1F5F7',
  },
} as const;

export const DESIGN_GRADIENTS = {
  primary: 'from-tertiary to-tertiary',
  secondary: 'from-primary to-primary',
  success: 'from-tertiary to-tertiary',
  warning: 'from-secondary to-secondary',
  danger: 'from-primary to-primary',
  info: 'from-secondary to-secondary',
} as const;

export const DESIGN_COLOR_SCALES = {
  primary: {
    gradient: DESIGN_GRADIENTS.primary,
    surface: DESIGN_TOKENS.brand.surface,
    surfaceSoft: DESIGN_TOKENS.brand.surfaceSoft,
    border: DESIGN_TOKENS.brand.border,
    text: DESIGN_TOKENS.brand.text,
    textStrong: DESIGN_TOKENS.brand.textStrong,
    icon: DESIGN_TOKENS.brand.icon,
  },
  secondary: {
    gradient: DESIGN_GRADIENTS.secondary,
    surface: 'bg-zinc-50',
    surfaceSoft: 'bg-zinc-50/80',
    border: 'border-zinc-200',
    text: 'text-zinc-600',
    textStrong: 'text-zinc-900',
    icon: 'text-zinc-500',
  },
  success: {
    gradient: DESIGN_GRADIENTS.success,
    surface: DESIGN_TOKENS.semantic.success.surface,
    surfaceSoft: 'bg-emerald-50/80',
    border: DESIGN_TOKENS.semantic.success.border,
    text: DESIGN_TOKENS.semantic.success.text,
    textStrong: DESIGN_TOKENS.semantic.success.textStrong,
    icon: DESIGN_TOKENS.semantic.success.icon,
  },
  warning: {
    gradient: DESIGN_GRADIENTS.warning,
    surface: DESIGN_TOKENS.semantic.warning.surface,
    surfaceSoft: 'bg-amber-50/80',
    border: DESIGN_TOKENS.semantic.warning.border,
    text: DESIGN_TOKENS.semantic.warning.text,
    textStrong: DESIGN_TOKENS.semantic.warning.textStrong,
    icon: DESIGN_TOKENS.semantic.warning.icon,
  },
  danger: {
    gradient: DESIGN_GRADIENTS.danger,
    surface: DESIGN_TOKENS.semantic.danger.surface,
    surfaceSoft: 'bg-rose-50/80',
    border: DESIGN_TOKENS.semantic.danger.border,
    text: DESIGN_TOKENS.semantic.danger.text,
    textStrong: DESIGN_TOKENS.semantic.danger.textStrong,
    icon: DESIGN_TOKENS.semantic.danger.icon,
  },
  info: {
    gradient: DESIGN_GRADIENTS.info,
    surface: DESIGN_TOKENS.semantic.info.surface,
    surfaceSoft: 'bg-blue-50/80',
    border: DESIGN_TOKENS.semantic.info.border,
    text: DESIGN_TOKENS.semantic.info.text,
    textStrong: DESIGN_TOKENS.semantic.info.textStrong,
    icon: DESIGN_TOKENS.semantic.info.icon,
  },
  neutral: {
    gradient: DESIGN_GRADIENTS.secondary,
    surface: DESIGN_TOKENS.semantic.neutral.surface,
    surfaceSoft: 'bg-zinc-50/80',
    border: DESIGN_TOKENS.semantic.neutral.border,
    text: DESIGN_TOKENS.semantic.neutral.text,
    textStrong: DESIGN_TOKENS.semantic.neutral.textStrong,
    icon: DESIGN_TOKENS.semantic.neutral.icon,
  },
} as const;
