export const DESIGN_TOKENS = {
  surfaces: {
    app: 'bg-app',
    appSoft: 'bg-app/50',
    canvas: 'bg-surface',
    muted: 'bg-surface-soft',
    overlay: 'bg-ink-soft/60',
  },
  text: {
    primary: 'text-ink',
    secondary: 'text-muted-2',
    muted: 'text-muted',
    subtle: 'text-muted-3',
    inverse: 'text-white',
    brand: 'text-brand',
    brandStrong: 'text-brand-600',
  },
  border: {
    default: 'border-line',
    soft: 'border-line-soft',
    strong: 'border-line-strong',
    brand: 'border-brand/40',
  },
  interactive: {
    primary: 'bg-brand text-white hover:bg-brand-600 focus:ring-brand/30',
    secondary: 'bg-surface text-ink border border-line hover:bg-surface-soft hover:border-line-strong focus:ring-brand/20',
    ghost: 'text-muted-2 hover:bg-surface-soft hover:text-ink focus:ring-brand/20',
  },
  brand: {
    surface: 'bg-surface-tint',
    surfaceSoft: 'bg-surface-soft',
    border: 'border-brand/40',
    text: 'text-brand',
    textStrong: 'text-brand-600',
    icon: 'text-brand',
    accent: 'bg-brand',
    accentHover: 'bg-brand-600',
  },
  semantic: {
    success: {
      surface: 'bg-status-success-bg',
      border: 'border-status-success-border',
      text: 'text-status-success-text',
      textStrong: 'text-status-success-text font-semibold',
      icon: 'text-status-success-text',
      badge: 'bg-status-success-bg text-status-success-text border border-status-success-border',
    },
    warning: {
      surface: 'bg-status-warning-bg',
      border: 'border-status-warning-border',
      text: 'text-status-warning-text',
      textStrong: 'text-status-warning-text font-semibold',
      icon: 'text-status-warning-text',
      badge: 'bg-status-warning-bg text-status-warning-text border border-status-warning-border',
    },
    danger: {
      surface: 'bg-status-danger-bg',
      border: 'border-status-danger-border',
      text: 'text-status-danger-text',
      textStrong: 'text-status-danger-text font-semibold',
      icon: 'text-status-danger-text',
      badge: 'bg-status-danger-bg text-status-danger-text border border-status-danger-border',
    },
    info: {
      surface: 'bg-status-info-bg',
      border: 'border-status-info-border',
      text: 'text-status-info-text',
      textStrong: 'text-status-info-text font-semibold',
      icon: 'text-status-info-text',
      badge: 'bg-status-info-bg text-status-info-text border border-status-info-border',
    },
    neutral: {
      surface: 'bg-surface-soft',
      border: 'border-line',
      text: 'text-muted-2',
      textStrong: 'text-ink font-semibold',
      icon: 'text-muted',
      badge: 'bg-surface-soft text-muted-2 border border-line',
    },
  },
  chart: {
    primary: '#0F2A3B',
    secondary: '#4F6B7C',
    tertiary: '#0E9F8E',
    quaternary: '#F1F5F7',
    success: '#0E9F8E',
    info: '#4F6B7C',
    warning: '#4F6B7C',
    danger: '#0F2A3B',
    muted: '#F1F5F7',
  },
} as const;

export const DESIGN_GRADIENTS = {
  primary: 'from-tertiary to-tertiary',
  secondary: 'from-primary to-primary',
  success: 'from-tertiary to-tertiary',
  warning: 'from-secondary to-secondary',
  danger: 'from-primary to-primary',
  info: 'from-secondary to-secondary',
} as const;

export const DESIGN_COLOR_SCALES = {
  primary: {
    gradient: DESIGN_GRADIENTS.primary,
    surface: DESIGN_TOKENS.brand.surface,
    surfaceSoft: DESIGN_TOKENS.brand.surfaceSoft,
    border: DESIGN_TOKENS.brand.border,
    text: DESIGN_TOKENS.brand.text,
    textStrong: DESIGN_TOKENS.brand.textStrong,
    icon: DESIGN_TOKENS.brand.icon,
  },
  secondary: {
    gradient: DESIGN_GRADIENTS.secondary,
    surface: 'bg-zinc-50',
    surfaceSoft: 'bg-zinc-50/80',
    border: 'border-zinc-200',
    text: 'text-zinc-600',
    textStrong: 'text-zinc-900',
    icon: 'text-zinc-500',
  },
  success: {
    gradient: DESIGN_GRADIENTS.success,
    surface: DESIGN_TOKENS.semantic.success.surface,
    surfaceSoft: 'bg-emerald-50/80',
    border: DESIGN_TOKENS.semantic.success.border,
    text: DESIGN_TOKENS.semantic.success.text,
    textStrong: DESIGN_TOKENS.semantic.success.textStrong,
    icon: DESIGN_TOKENS.semantic.success.icon,
  },
  warning: {
    gradient: DESIGN_GRADIENTS.warning,
    surface: DESIGN_TOKENS.semantic.warning.surface,
    surfaceSoft: 'bg-amber-50/80',
    border: DESIGN_TOKENS.semantic.warning.border,
    text: DESIGN_TOKENS.semantic.warning.text,
    textStrong: DESIGN_TOKENS.semantic.warning.textStrong,
    icon: DESIGN_TOKENS.semantic.warning.icon,
  },
  danger: {
    gradient: DESIGN_GRADIENTS.danger,
    surface: DESIGN_TOKENS.semantic.danger.surface,
    surfaceSoft: 'bg-rose-50/80',
    border: DESIGN_TOKENS.semantic.danger.border,
    text: DESIGN_TOKENS.semantic.danger.text,
    textStrong: DESIGN_TOKENS.semantic.danger.textStrong,
    icon: DESIGN_TOKENS.semantic.danger.icon,
  },
  info: {
    gradient: DESIGN_GRADIENTS.info,
    surface: DESIGN_TOKENS.semantic.info.surface,
    surfaceSoft: 'bg-blue-50/80',
    border: DESIGN_TOKENS.semantic.info.border,
    text: DESIGN_TOKENS.semantic.info.text,
    textStrong: DESIGN_TOKENS.semantic.info.textStrong,
    icon: DESIGN_TOKENS.semantic.info.icon,
  },
  neutral: {
    gradient: DESIGN_GRADIENTS.secondary,
    surface: DESIGN_TOKENS.semantic.neutral.surface,
    surfaceSoft: 'bg-zinc-50/80',
    border: DESIGN_TOKENS.semantic.neutral.border,
    text: DESIGN_TOKENS.semantic.neutral.text,
    textStrong: DESIGN_TOKENS.semantic.neutral.textStrong,
    icon: DESIGN_TOKENS.semantic.neutral.icon,
  },
} as const;
