import {
  BellRing,
  Blocks,
  Building2,
  Globe2,
  Layers3,
  Mail,
  Server,
  Settings2,
  ShieldCheck,
  Siren,
} from 'lucide-react';
import type {
  ConfiguracionCategoryDefinition,
  ConfiguracionFieldDefinition,
  ConfiguracionGroupDefinition,
  ConfiguracionNavGroup,
} from './types';

export const CONFIG_GROUPS: ConfiguracionGroupDefinition[] = [
  {
    id: 'identidad',
    label: 'Identidad',
    contextLabel: 'Identidad y experiencia',
    description: 'Marca institucional, metadatos publicos y preferencias visibles.',
    icon: Building2,
    category: 'experiencia',
    path: '/configuracion/identidad',
  },
  {
    id: 'alertas',
    label: 'Alertas',
    contextLabel: 'Alertas y notificaciones',
    description: 'Umbrales operativos y comunicacion del sistema.',
    icon: BellRing,
    category: 'experiencia',
    path: '/configuracion/alertas',
  },
  {
    id: 'seguridad',
    label: 'Seguridad',
    contextLabel: 'Seguridad y acceso',
    description: 'Parametros de acceso y endurecimiento con trazabilidad.',
    icon: ShieldCheck,
    category: 'plataforma',
    path: '/configuracion/seguridad',
  },
  {
    id: 'operacion',
    label: 'Operacion',
    contextLabel: 'Operacion y sistema',
    description: 'Respaldos, reportes, API y diagnostico del sistema.',
    icon: Server,
    category: 'plataforma',
    path: '/configuracion/operacion',
  },
];

export const CONFIG_NAV_GROUPS: ConfiguracionNavGroup[] = [
  {
    key: 'experiencia',
    label: 'Experiencia',
    description: 'Lo que el equipo ve y ajusta dia a dia.',
    icon: Layers3,
  },
  {
    key: 'plataforma',
    label: 'Plataforma',
    description: 'Controles avanzados, seguridad y operacion tecnica.',
    icon: Settings2,
  },
];

export const CONFIG_CATEGORIES: ConfiguracionCategoryDefinition[] = [
  {
    id: 'general',
    groupId: 'identidad',
    label: 'Identidad institucional',
    description: 'Datos usados en documentos, cabeceras y metadatos publicos.',
    icon: Building2,
    editable: true,
    source: 'database',
  },
  {
    id: 'alertas',
    groupId: 'alertas',
    label: 'Umbrales activos',
    description: 'Valores usados al ejecutar acciones operativas desde este modulo.',
    icon: Siren,
    editable: true,
    source: 'database',
  },
  {
    id: 'notificaciones',
    groupId: 'alertas',
    label: 'Canales y envio',
    description: 'Configuracion registrada; el runtime actual no consume estos flags desde la base.',
    icon: Mail,
    editable: false,
    source: 'database',
    runtimeNote: 'El envio real sigue gobernado por la configuracion tecnica del servidor.',
  },
  {
    id: 'seguridad',
    groupId: 'seguridad',
    label: 'Politicas registradas',
    description: 'Parametros persistidos para referencia operativa y futura conexion runtime.',
    icon: ShieldCheck,
    editable: false,
    source: 'database',
    runtimeNote: 'El tiempo real de sesion y validaciones criticas aun no toman estos valores desde la base.',
  },
  {
    id: 'backup',
    groupId: 'operacion',
    label: 'Respaldos',
    description: 'El runtime del backend usa variables de entorno para estos controles.',
    icon: Blocks,
    editable: false,
    source: 'env',
    runtimeNote: 'Se muestra la configuracion registrada, pero la ejecucion real depende del servidor.',
  },
  {
    id: 'reportes',
    groupId: 'operacion',
    label: 'Limites de reportes',
    description: 'Parametros almacenados para operacion avanzada y observabilidad.',
    icon: Globe2,
    editable: false,
    source: 'database',
    runtimeNote: 'Todavia no existe un consumidor global uniforme en frontend o backend.',
  },
  {
    id: 'api',
    groupId: 'operacion',
    label: 'API y rate limiting',
    description: 'El rate limiting productivo sigue viniendo de variables de entorno.',
    icon: Settings2,
    editable: false,
    source: 'env',
    runtimeNote: 'Los limites reales del servidor no leen estos registros desde la base.',
  },
  {
    id: 'sistema',
    groupId: 'operacion',
    label: 'Diagnostico del sistema',
    description: 'Lectura operativa del estado visible del modulo.',
    icon: Server,
    editable: false,
    source: 'derived',
  },
];

export const CONFIG_FIELDS: ConfiguracionFieldDefinition[] = [
  {
    id: 'sistemaNombre',
    key: 'sistema_nombre',
    groupId: 'identidad',
    categoryId: 'general',
    label: 'Nombre del sistema',
    description: 'Nombre publico de la plataforma en vistas y documentos.',
    placeholder: 'SIVAC - Sistema de Gestion de Vacunas',
    type: 'text',
    editable: true,
    source: 'database',
    status: 'editable',
    defaultValue: 'SIVAC - Sistema de Gestion de Vacunas',
    createMeta: {
      categoria: 'general',
      tipoDato: 'string',
      esPublico: true,
      descripcion: 'Nombre del sistema',
    },
  },
  {
    id: 'institucionNombre',
    key: 'institucion_nombre',
    groupId: 'identidad',
    categoryId: 'general',
    label: 'Institucion',
    description: 'Nombre institucional usado en exportaciones y encabezados.',
    placeholder: 'Direccion de Salud Apurimac II',
    type: 'text',
    editable: true,
    source: 'database',
    status: 'editable',
    defaultValue: 'DISA Apurimac II',
    createMeta: {
      categoria: 'general',
      tipoDato: 'string',
      esPublico: true,
      descripcion: 'Nombre de la institucion',
    },
  },
  {
    id: 'institucionDireccion',
    key: 'institucion_direccion',
    groupId: 'identidad',
    categoryId: 'general',
    label: 'Direccion institucional',
    description: 'Direccion de referencia para documentos y ficha del sistema.',
    placeholder: 'Jr. Lima 123, Andahuaylas, Apurimac',
    type: 'textarea',
    editable: true,
    source: 'database',
    status: 'editable',
    rows: 3,
    defaultValue: 'Jr. Lima 123, Andahuaylas, Apurimac',
    createMeta: {
      categoria: 'general',
      tipoDato: 'string',
      esPublico: true,
    },
  },
  {
    id: 'institucionTelefono',
    key: 'institucion_telefono',
    groupId: 'identidad',
    categoryId: 'general',
    label: 'Telefono',
    description: 'Contacto operativo visible para usuarios internos.',
    placeholder: '+51 983 456 789',
    type: 'tel',
    editable: true,
    source: 'database',
    status: 'editable',
    defaultValue: '+51 983 456 789',
    createMeta: {
      categoria: 'general',
      tipoDato: 'string',
      esPublico: true,
    },
  },
  {
    id: 'institucionEmail',
    key: 'institucion_email',
    groupId: 'identidad',
    categoryId: 'general',
    label: 'Correo institucional',
    description: 'Contacto principal mostrado por el sistema.',
    placeholder: 'contacto@saludapurimac.gob.pe',
    type: 'email',
    editable: true,
    source: 'database',
    status: 'editable',
    defaultValue: 'contacto@saludapurimac.gob.pe',
    createMeta: {
      categoria: 'general',
      tipoDato: 'string',
      esPublico: true,
    },
  },
  {
    id: 'timezone',
    key: 'timezone',
    groupId: 'identidad',
    categoryId: 'general',
    label: 'Zona horaria',
    description: 'Metadato base del sistema y exportaciones.',
    type: 'select',
    editable: true,
    source: 'database',
    status: 'editable',
    defaultValue: 'America/Lima',
    options: [
      { value: 'America/Lima', label: 'Lima (UTC-5)' },
      { value: 'America/Bogota', label: 'Bogota (UTC-5)' },
      { value: 'America/Mexico_City', label: 'Ciudad de Mexico (UTC-6)' },
    ],
    createMeta: {
      categoria: 'general',
      tipoDato: 'string',
      esPublico: false,
      descripcion: 'Zona horaria del sistema',
    },
  },
  {
    id: 'formatoFecha',
    key: 'formato_fecha',
    groupId: 'identidad',
    categoryId: 'general',
    label: 'Formato de fecha',
    description: 'Formato visible para documentos y datos exportados.',
    type: 'select',
    editable: true,
    source: 'database',
    status: 'editable',
    defaultValue: 'DD/MM/YYYY',
    options: [
      { value: 'DD/MM/YYYY', label: 'DD/MM/YYYY' },
      { value: 'MM/DD/YYYY', label: 'MM/DD/YYYY' },
      { value: 'YYYY-MM-DD', label: 'YYYY-MM-DD' },
    ],
    createMeta: {
      categoria: 'general',
      tipoDato: 'string',
      esPublico: true,
    },
  },
  {
    id: 'anioNombre',
    key: 'anio_nombre',
    groupId: 'identidad',
    categoryId: 'general',
    label: 'Nombre oficial del ano',
    description: 'Texto extendido usado en reportes y exportaciones institucionales.',
    placeholder: 'Ej: Ano de la recuperacion y consolidacion...',
    type: 'textarea',
    editable: true,
    source: 'database',
    status: 'editable',
    rows: 3,
    defaultValue: '',
    createMeta: {
      categoria: 'general',
      tipoDato: 'string',
      esPublico: true,
    },
  },
  {
    id: 'diasAlertaVencimiento',
    key: 'dias_alerta_vencimiento',
    legacyKeys: ['alertas_dias_anticipacion'],
    groupId: 'alertas',
    categoryId: 'alertas',
    label: 'Anticipacion de vencimiento',
    description: 'Dias previos al vencimiento para priorizar revision y generacion de alertas.',
    type: 'number',
    editable: true,
    source: 'database',
    status: 'editable',
    min: 1,
    max: 180,
    step: 1,
    defaultValue: 30,
    formatValue: (value) => `${value} dias`,
    createMeta: {
      categoria: 'alertas',
      tipoDato: 'number',
      esPublico: false,
      descripcion: 'Dias antes del vencimiento para generar alerta',
    },
  },
  {
    id: 'stockMinimoDefault',
    key: 'stock_minimo_default',
    legacyKeys: ['alertas_stock_minimo'],
    groupId: 'alertas',
    categoryId: 'alertas',
    label: 'Stock minimo de referencia',
    description: 'Umbral base usado al ejecutar la generacion automatica desde este modulo.',
    type: 'number',
    editable: true,
    source: 'database',
    status: 'editable',
    min: 1,
    max: 100000,
    step: 1,
    defaultValue: 100,
    createMeta: {
      categoria: 'alertas',
      tipoDato: 'number',
      esPublico: false,
      descripcion: 'Stock minimo por defecto para alertas',
    },
  },
  {
    id: 'notificationsEnabled',
    key: 'notifications_enabled',
    groupId: 'alertas',
    categoryId: 'notificaciones',
    label: 'Notificaciones del sistema',
    description: 'Flag persistido para notificaciones generales.',
    type: 'text',
    editable: false,
    source: 'database',
    status: 'stored',
    defaultValue: 'true',
  },
  {
    id: 'alertasEmailEnabled',
    key: 'alertas_email_enabled',
    groupId: 'alertas',
    categoryId: 'notificaciones',
    label: 'Alertas por correo',
    description: 'Valor registrado para correo de alertas.',
    type: 'text',
    editable: false,
    source: 'database',
    status: 'stored',
    defaultValue: 'false',
  },
  {
    id: 'emailFrom',
    key: 'email_from',
    groupId: 'alertas',
    categoryId: 'notificaciones',
    label: 'Remitente',
    description: 'Direccion remitente registrada en la base.',
    type: 'email',
    editable: false,
    source: 'database',
    status: 'stored',
    defaultValue: 'noreply@saludapurimac.gob.pe',
  },
  {
    id: 'sessionTimeout',
    key: 'session_timeout',
    legacyKeys: ['tiempo_sesion'],
    groupId: 'seguridad',
    categoryId: 'seguridad',
    label: 'Expiracion de sesion',
    description: 'Tiempo persistido para expiracion; el runtime actual usa configuracion tecnica separada.',
    type: 'number',
    editable: false,
    source: 'database',
    status: 'stored',
    defaultValue: 1440,
    formatValue: (value) => `${value} min`,
  },
  {
    id: 'maxLoginAttempts',
    key: 'max_login_attempts',
    groupId: 'seguridad',
    categoryId: 'seguridad',
    label: 'Maximo de intentos de login',
    description: 'Valor de referencia almacenado para politicas de acceso.',
    type: 'number',
    editable: false,
    source: 'database',
    status: 'stored',
    defaultValue: 5,
  },
  {
    id: 'passwordMinLength',
    key: 'password_min_length',
    groupId: 'seguridad',
    categoryId: 'seguridad',
    label: 'Longitud minima de contrasena',
    description: 'Longitud registrada; la validacion activa del backend aun es fija.',
    type: 'number',
    editable: false,
    source: 'database',
    status: 'stored',
    defaultValue: 8,
  },
  {
    id: 'backupEnabled',
    key: 'backup_enabled',
    groupId: 'operacion',
    categoryId: 'backup',
    label: 'Respaldos automaticos',
    description: 'El backend productivo resuelve este valor desde variables de entorno.',
    type: 'text',
    editable: false,
    source: 'env',
    status: 'env',
    defaultValue: 'false',
  },
  {
    id: 'backupSchedule',
    key: 'backup_schedule',
    groupId: 'operacion',
    categoryId: 'backup',
    label: 'Programacion de respaldo',
    description: 'Cron registrado en la base para referencia operativa.',
    type: 'text',
    editable: false,
    source: 'env',
    status: 'env',
    defaultValue: '0 2 * * *',
  },
  {
    id: 'backupRetentionDays',
    key: 'backup_retention_days',
    groupId: 'operacion',
    categoryId: 'backup',
    label: 'Retencion de respaldos',
    description: 'Cantidad de dias almacenada para respaldo.',
    type: 'number',
    editable: false,
    source: 'env',
    status: 'env',
    defaultValue: 30,
    formatValue: (value) => `${value} dias`,
  },
  {
    id: 'reportesCacheDuration',
    key: 'reportes_cache_duration',
    groupId: 'operacion',
    categoryId: 'reportes',
    label: 'Cache de reportes',
    description: 'Duracion registrada para cache de reportes.',
    type: 'number',
    editable: false,
    source: 'database',
    status: 'stored',
    defaultValue: 300,
    formatValue: (value) => `${value} s`,
  },
  {
    id: 'reportesMaxRegistros',
    key: 'reportes_max_registros',
    groupId: 'operacion',
    categoryId: 'reportes',
    label: 'Maximo de registros',
    description: 'Limite guardado para consultas masivas de reportes.',
    type: 'number',
    editable: false,
    source: 'database',
    status: 'stored',
    defaultValue: 10000,
  },
  {
    id: 'apiRateLimit',
    key: 'api_rate_limit',
    groupId: 'operacion',
    categoryId: 'api',
    label: 'Requests por ventana',
    description: 'Referencia registrada; el rate limiting real del servidor usa `.env`.',
    type: 'number',
    editable: false,
    source: 'env',
    status: 'env',
    defaultValue: 100,
  },
  {
    id: 'apiRateWindow',
    key: 'api_rate_window',
    groupId: 'operacion',
    categoryId: 'api',
    label: 'Ventana de rate limit',
    description: 'Ventana registrada en milisegundos.',
    type: 'number',
    editable: false,
    source: 'env',
    status: 'env',
    defaultValue: 900000,
    formatValue: (value) => `${Math.round(Number(value) / 60000)} min`,
  },
  {
    id: 'sistemaVersion',
    key: 'sistema_version',
    groupId: 'operacion',
    categoryId: 'sistema',
    label: 'Version del sistema',
    description: 'Version visible para diagnostico del modulo.',
    type: 'text',
    editable: false,
    source: 'database',
    status: 'stored',
    defaultValue: '1.0.0',
  },
];

export const getGroupById = (groupId: string) => CONFIG_GROUPS.find((group) => group.id === groupId);
export const getCategoryById = (categoryId: string) => CONFIG_CATEGORIES.find((category) => category.id === categoryId);
export const getFieldsByGroup = (groupId: string) => CONFIG_FIELDS.filter((field) => field.groupId === groupId);
export const getFieldsByCategory = (categoryId: string) => CONFIG_FIELDS.filter((field) => field.categoryId === categoryId);
export const getEditableFieldsByGroup = (groupId: string) =>
  CONFIG_FIELDS.filter((field) => field.groupId === groupId && field.editable);
